### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jxn78** [KitsuneLab-Development/K4-Arenas#31] opened 2024-11-12 20:08 UTC
![IMG_20241112_205600](https://github.com/user-attachments/assets/0f25211d-beb8-4169-819f-838e6497c66e)

**Comment by jxn78** [comment] 2024-11-12 20:08
@K4ryuu @originalaidn help me

**Comment by K4ryuu** [comment] 2024-11-16 00:59
I pushed a new release with updated CounterStrikeSharp API. Possibly that fixes your issue, but please give me a feedback about that.

**Comment by jxn78** [comment] 2024-12-03 07:51
@K4ryuu 
`08:47:21 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid game event
   at CounterStrikeSharp.API.Core.NativeAPI.GetEventPlayerController(IntPtr gameevent, String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 965
   at CounterStrikeSharp.API.Modules.Events.GameEvent.GetPlayer(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Events/GameEvent.cs:line 111
   at K4Arenas.Plugin.<>c.<Initialize_Events>b__55_10(EventRoundMvp event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100`

**Comment by jxn78** [comment] 2024-12-03 07:51
pls help me

**Comment by K4ryuu** [comment] 2024-12-04 22:03
Did you updated the plugin to https://github.com/KitsuneLab-Development/K4-Arenas/releases/tag/v1.5.2?

**Comment by jxn78** [comment] 2024-12-05 06:32
yes

**Comment by K4ryuu** [comment] 2024-12-09 15:27
I cannot reproduce the issue with the latest build, so I close the issue.
I recommend you to update your CSS, keep the files, gamedata up-to-date.

In worts case scenario download runtime version and update full CSS.

**Closed as completed by K4ryuu** 2024-12-09 15:27 UTC
Labels: Bug, Priority: Medium
